name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - working-directory: ./Task1FGTC
      run: composer install --prefer-dist --no-progress
    - working-directory: ./Task1FGTC
      run: composer exec phpunit tests
      name: Task1FGTC unit tests

    - working-directory: ./Task7RFACount
      run: composer install --prefer-dist --no-progress
    - working-directory: ./Task7RFACount
      run: composer exec phpunit tests
      name: Task7RFACount unit tests

    - working-directory: ./TaskAPerms
      run: composer install --prefer-dist --no-progress
    - working-directory: ./TaskAPerms
      run: composer exec phpunit tests
      name: TaskAPerms unit tests