name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: composer install
      run: composer install --prefer-dist --no-progress
    
    - name: composer exec phpunit tests
      run: composer exec phpunit tests
